java-library: inherit allarch
Use the allarch class to make every packages in the 'all' ARCH.
Recipes inheriting java-library which build additional packages which
don't belong in to all ARCH must manually setting PACKAGE_ARCH after
inheritting java-library.

This fixes the following error when building e.g. rhino for a second
machine of different architecture in the same build directory:
    ERROR: The recipe rhino is trying to install files into a
    shared area when those files already exist. Those files and their
    manifest location are:
       /.../ipk/all/librhino-java_1.7r4-r0_all.ipk
    Matched in manifest-armv7at2hf-vfp-rhino-package_write_ipk

Signed-off-by: Max Krummenacher <max.oss.09@gmail.com>
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>

Conflicts:
	recipes-extended/rxtx/rxtx_2.2.0.bb